import { Ciudad, Frequency, MARegion, MIRegion, Pais, Provincia, Sector, UserType } from "../../Modules/models/index.js";
import sequelizeInstance from "../../config/sequelize.config.js";
import LoanState from "../../Modules/models/LoanState.js";

export const insertData = async (req, res) => {
    const t = await sequelizeInstance.transaction();

    try {
        await UserType.bulkCreate([
            { NameType: 'superUser' },
            { NameType: 'tenant' },
            { NameType: 'Admin' },
            { NameType: 'customer' },
            { NameType: 'guest' }
        ], { transaction: t })

        // Insertar en la tabla Pais
        await Pais.bulkCreate([
            { PaisId: 'DO', NombrePais: 'República Dominicana' },

        ], { transaction: t });

        // Insertar en la tabla MARegion
        await MARegion.bulkCreate([
            { PaisId: 'DO', NombreRegion: 'Cibao' },
            { PaisId: 'DO', NombreRegion: 'Sur' },
            { PaisId: 'DO', NombreRegion: 'Oriental o Este' }
        ], { transaction: t });

        // Insertar en la tabla MIRegion
        await MIRegion.bulkCreate([
            // Cibao
            { MARegionId: 1, NombreRegion: 'Cibao Norte', RegionColor: 'Verde' },
            { MARegionId: 1, NombreRegion: 'Cibao Sur', RegionColor: 'Azul' },
            { MARegionId: 1, NombreRegion: 'Cibao Nordeste', RegionColor: 'Amarillo' },
            { MARegionId: 1, NombreRegion: 'Cibao Noroeste', RegionColor: 'Rojo' },

            // Sur
            { MARegionId: 2, NombreRegion: 'Valdesia', RegionColor: 'Naranja' },
            { MARegionId: 2, NombreRegion: 'El Valle', RegionColor: 'Naranja' },
            { MARegionId: 2, NombreRegion: 'Enriquillo', RegionColor: 'Naranja' },

            // Oriental o Este
            { MARegionId: 3, NombreRegion: 'Yuma', RegionColor: 'Violeta' },
            { MARegionId: 3, NombreRegion: 'Higuamo', RegionColor: 'Violeta' },
            { MARegionId: 3, NombreRegion: 'Ozama', RegionColor: 'Violeta' }
        ], { transaction: t });

        // Insertar en la tabla Provincia
        await Provincia.bulkCreate([
            // Cibao
            { PaisId: 'DO', MIRegionId: 1, NombreProvincia: 'Espaillat' },
            { PaisId: 'DO', MIRegionId: 1, NombreProvincia: 'Puerto Plata' },
            { PaisId: 'DO', MIRegionId: 1, NombreProvincia: 'Santiago' },

            { PaisId: 'DO', MIRegionId: 2, NombreProvincia: 'La Vega' },
            { PaisId: 'DO', MIRegionId: 2, NombreProvincia: 'Monseñor Nouel' },
            { PaisId: 'DO', MIRegionId: 2, NombreProvincia: 'Sánchez Ramírez' },

            { PaisId: 'DO', MIRegionId: 3, NombreProvincia: 'Duarte' },
            { PaisId: 'DO', MIRegionId: 3, NombreProvincia: 'Hermanas Mirabal' },
            { PaisId: 'DO', MIRegionId: 3, NombreProvincia: 'María Trinidad Sánchez' },
            { PaisId: 'DO', MIRegionId: 3, NombreProvincia: 'Samaná' },

            { PaisId: 'DO', MIRegionId: 4, NombreProvincia: 'Dajabón' },
            { PaisId: 'DO', MIRegionId: 4, NombreProvincia: 'Monte Cristi' },
            { PaisId: 'DO', MIRegionId: 4, NombreProvincia: 'Santiago Rodríguez' },
            { PaisId: 'DO', MIRegionId: 4, NombreProvincia: 'Valverde' },

            // Sur
            { PaisId: 'DO', MIRegionId: 5, NombreProvincia: 'Azua' },
            { PaisId: 'DO', MIRegionId: 5, NombreProvincia: 'Peravia' },
            { PaisId: 'DO', MIRegionId: 5, NombreProvincia: 'San José de Ocoa' },
            { PaisId: 'DO', MIRegionId: 5, NombreProvincia: 'San Cristóbal' },

            // Oriental o Este
            { PaisId: 'DO', MIRegionId: 6, NombreProvincia: 'Elías Piña' },
            { PaisId: 'DO', MIRegionId: 6, NombreProvincia: 'San Juan' },

            { PaisId: 'DO', MIRegionId: 7, NombreProvincia: 'Barahona' },
            { PaisId: 'DO', MIRegionId: 7, NombreProvincia: 'Bahoruco' },
            { PaisId: 'DO', MIRegionId: 7, NombreProvincia: 'Independencia' },
            { PaisId: 'DO', MIRegionId: 7, NombreProvincia: 'Pedernales' },

            { PaisId: 'DO', MIRegionId: 8, NombreProvincia: 'La Romana' },
            { PaisId: 'DO', MIRegionId: 8, NombreProvincia: 'La Altagracia' },
            { PaisId: 'DO', MIRegionId: 8, NombreProvincia: 'El Seibo' },

            { PaisId: 'DO', MIRegionId: 9, NombreProvincia: 'Hato Mayor' },
            { PaisId: 'DO', MIRegionId: 9, NombreProvincia: 'Monte Plata' },
            { PaisId: 'DO', MIRegionId: 9, NombreProvincia: 'San Pedro de Macorís' },

            { PaisId: 'DO', MIRegionId: 10, NombreProvincia: 'Distrito Nacional' },
            { PaisId: 'DO', MIRegionId: 10, NombreProvincia: 'Santo Domingo' },

        ], { transaction: t });

        // Insertar en la tabla Ciudad
        await Ciudad.bulkCreate([
            { ProvinciaId: 32, NombreCiudad: 'Santo Domingo Este' },
            { ProvinciaId: 31, NombreCiudad: 'Distrito Nacional' },
            { ProvinciaId: 3, NombreCiudad: 'Santiago de los Caballeros' },
            { ProvinciaId: 32, NombreCiudad: 'Santo Domingo Norte' },
            { ProvinciaId: 32, NombreCiudad: 'Santo Domingo Oeste' },
            { ProvinciaId: 32, NombreCiudad: 'Los Alcarrizos' },
            { ProvinciaId: 26, NombreCiudad: 'Higüey' },
            { ProvinciaId: 18, NombreCiudad: 'San Cristóbal' },
            { ProvinciaId: 4, NombreCiudad: 'La Vega' },
            { ProvinciaId: 30, NombreCiudad: 'San Pedro de Macorís' },
            { ProvinciaId: 7, NombreCiudad: 'San Francisco de Macorís' },
            { ProvinciaId: 1, NombreCiudad: 'Moca' },
            { ProvinciaId: 32, NombreCiudad: 'Boca Chica' },
            { ProvinciaId: 16, NombreCiudad: 'Baní' },
            { ProvinciaId: 2, NombreCiudad: 'Puerto Plata' },
            { ProvinciaId: 25, NombreCiudad: 'La Romana' },
            { ProvinciaId: 8, NombreCiudad: 'Bajos de Haina' },
            { ProvinciaId: 5, NombreCiudad: 'Bonao' },
            { ProvinciaId: 20, NombreCiudad: 'San Juan' },
            { ProvinciaId: 26, NombreCiudad: 'Villa Hermosa' },
            { ProvinciaId: 8, NombreCiudad: 'Villa Altagracia' },
            { ProvinciaId: 32, NombreCiudad: 'Pedro Brand' },
            { ProvinciaId: 21, NombreCiudad: 'Barahona' },
            { ProvinciaId: 14, NombreCiudad: 'Mao' },
            { ProvinciaId: 10, NombreCiudad: 'Nagua' },
            { ProvinciaId: 6, NombreCiudad: 'Cotuí' },
            { ProvinciaId: 27, NombreCiudad: 'El Seibo' },
            { ProvinciaId: 14, NombreCiudad: 'Esperanza' },
            { ProvinciaId: 10, NombreCiudad: 'Samaná' },
            { ProvinciaId: 9, NombreCiudad: 'Hato Mayor' },
            { ProvinciaId: 8, NombreCiudad: 'Constanza' },
            { ProvinciaId: 8, NombreCiudad: 'Jarabacoa' },
            { ProvinciaId: 29, NombreCiudad: 'Yamasá' },
            { ProvinciaId: 3, NombreCiudad: 'Tamboril' },
            { ProvinciaId: 32, NombreCiudad: 'San Antonio de Guerra' },
            { ProvinciaId: 15, NombreCiudad: 'Sosúa' },
            { ProvinciaId: 3, NombreCiudad: 'Puñal' },
            { ProvinciaId: 28, NombreCiudad: 'Monte Plata' },
            { ProvinciaId: 3, NombreCiudad: 'Villa Bisonó' },
            { ProvinciaId: 19, NombreCiudad: 'Las Matas de Farfán' },
            { ProvinciaId: 3, NombreCiudad: 'San José de las Matas' },
            { ProvinciaId: 9, NombreCiudad: 'Salcedo' },
            { ProvinciaId: 13, NombreCiudad: 'La Mata' },
            { ProvinciaId: 1, NombreCiudad: 'Gaspar Hernández' },
            { ProvinciaId: 12, NombreCiudad: 'Guayubín' },
            { ProvinciaId: 22, NombreCiudad: 'Neiba' },
            { ProvinciaId: 17, NombreCiudad: 'San José de Ocoa' },
            { ProvinciaId: 7, NombreCiudad: 'Villa Riva' },
            { ProvinciaId: 13, NombreCiudad: 'San Ignacio de Sabaneta' },
            { ProvinciaId: 29, NombreCiudad: 'Bayaguana' },
            { ProvinciaId: 11, NombreCiudad: 'Dajabón' },
            { ProvinciaId: 11, NombreCiudad: 'Tenares' },
            { ProvinciaId: 3, NombreCiudad: 'Villa González' },
            { ProvinciaId: 14, NombreCiudad: 'Monte Cristi' },
            { ProvinciaId: 6, NombreCiudad: 'La Cueva' },
            { ProvinciaId: 6, NombreCiudad: 'Cevicos' },
            { ProvinciaId: 6, NombreCiudad: 'Fantino' },
            { ProvinciaId: 5, NombreCiudad: 'Piedra Blanca' },
            { ProvinciaId: 5, NombreCiudad: 'Maimón' },
            { ProvinciaId: 5, NombreCiudad: 'Sabana del Puerto' },
            { ProvinciaId: 23, NombreCiudad: 'Jimaní' },
            { ProvinciaId: 23, NombreCiudad: 'Duvergé' },
            { ProvinciaId: 23, NombreCiudad: 'La Descubierta' },
            { ProvinciaId: 23, NombreCiudad: 'Mella' },
            { ProvinciaId: 24, NombreCiudad: 'Pedernales' },
            { ProvinciaId: 24, NombreCiudad: 'Oviedo' },
            { ProvinciaId: 24, NombreCiudad: 'Juancho' },
            { ProvinciaId: 24, NombreCiudad: 'Bahía de las Águilas' },
        ], { transaction: t });

        const sectorsData = [
            { CiudadId: 1, NombreSector: 'Alma Rosa' },
            { CiudadId: 1, NombreSector: 'San Isidro' },
            { CiudadId: 1, NombreSector: 'Invivienda' },
            { CiudadId: 1, NombreSector: 'Los Mina' },
            { CiudadId: 1, NombreSector: 'Villa Faro' },
            { CiudadId: 1, NombreSector: 'Villa Duarte' },
            { CiudadId: 1, NombreSector: 'Mendoza' },
            { CiudadId: 1, NombreSector: 'San Luis' },
            { CiudadId: 1, NombreSector: 'Autopista de San Isidro' },
            { CiudadId: 1, NombreSector: 'Brisas del Este' },

            // Distrito Nacional
            { CiudadId: 2, NombreSector: 'Gazcue' },
            { CiudadId: 2, NombreSector: 'Naco' },
            { CiudadId: 2, NombreSector: 'Ensanche Quisqueya' },
            { CiudadId: 2, NombreSector: 'Bella Vista' },
            { CiudadId: 2, NombreSector: 'Piantini' },
            { CiudadId: 2, NombreSector: 'Evaristo Morales' },
            { CiudadId: 2, NombreSector: 'Los Prados' },
            { CiudadId: 2, NombreSector: 'Mirador Sur' },
            { CiudadId: 2, NombreSector: 'Zona Universitaria' },
            { CiudadId: 2, NombreSector: 'Villa Consuelo' },

            // Santiago de los Caballeros
            { CiudadId: 3, NombreSector: 'Gurabo' },
            { CiudadId: 3, NombreSector: 'Bella Vista' },
            { CiudadId: 3, NombreSector: 'Los Jardines Metropolitanos' },
            { CiudadId: 3, NombreSector: 'Villa Olga' },
            { CiudadId: 3, NombreSector: 'Cienfuegos' },
            { CiudadId: 3, NombreSector: 'Ensanche Bermúdez' },
            { CiudadId: 3, NombreSector: 'Pontezuela' },
            { CiudadId: 3, NombreSector: 'La Trinitaria' },
            { CiudadId: 3, NombreSector: 'Barrio Duarte' },
            { CiudadId: 3, NombreSector: 'Villa María' },

            // Santo Domingo Norte
            { CiudadId: 4, NombreSector: 'Villa Mella' },
            { CiudadId: 4, NombreSector: 'Los Guaricanos' },
            { CiudadId: 4, NombreSector: 'Sabana Perdida' },
            { CiudadId: 4, NombreSector: 'La Victoria' },
            { CiudadId: 4, NombreSector: 'Los Alcarrizos' },
            { CiudadId: 4, NombreSector: 'La Javilla' },
            { CiudadId: 4, NombreSector: 'El Café' },
            { CiudadId: 4, NombreSector: 'Los Tres Brazos' },
            { CiudadId: 4, NombreSector: 'La Nueva Barquita' },
            { CiudadId: 4, NombreSector: 'Buenos Aires' },

            // Higüey
            { CiudadId: 7, NombreSector: 'La Otra Banda' },
            { CiudadId: 7, NombreSector: 'Verón' },
            { CiudadId: 7, NombreSector: 'Bávaro' },
            { CiudadId: 7, NombreSector: 'Punta Cana' },
            { CiudadId: 7, NombreSector: 'El Bonao' },
            { CiudadId: 7, NombreSector: 'San Rafael del Yuma' },
            { CiudadId: 7, NombreSector: 'La Romana' },
            { CiudadId: 7, NombreSector: 'Bayahibe' },
            { CiudadId: 7, NombreSector: 'Boca de Yuma' },
            { CiudadId: 7, NombreSector: 'Anamuya' },

            // Santo Domingo Oeste
            { CiudadId: 5, NombreSector: 'Herrera' },
            { CiudadId: 5, NombreSector: 'Los Alcarrizos' },
            { CiudadId: 5, NombreSector: 'Pantoja' },
            { CiudadId: 5, NombreSector: 'Manoguayabo' },
            { CiudadId: 5, NombreSector: 'Palmarejo' },
            { CiudadId: 5, NombreSector: 'La Ciénaga' },
            { CiudadId: 5, NombreSector: 'Las Caobas' },
            { CiudadId: 5, NombreSector: 'La Venta' },
            { CiudadId: 5, NombreSector: 'Kilómetro 9' },
            { CiudadId: 5, NombreSector: 'Las Palmas' },

            // Los Alcarrizos
            { CiudadId: 6, NombreSector: 'Los Alcarrizos Centro' },
            { CiudadId: 6, NombreSector: 'Buenos Aires' },
            { CiudadId: 6, NombreSector: 'Hato Nuevo' },
            { CiudadId: 6, NombreSector: 'Palmarejito' },
            { CiudadId: 6, NombreSector: 'Sabana Perdida' },
            { CiudadId: 6, NombreSector: 'Las Mercedes' },
            { CiudadId: 6, NombreSector: 'El Libertador' },
            { CiudadId: 6, NombreSector: 'El Café' },
            { CiudadId: 6, NombreSector: 'La 40' },
            { CiudadId: 6, NombreSector: 'Las 100 Casas' },

            { CiudadId: 9, NombreSector: 'La Vega Centro' },
            { CiudadId: 9, NombreSector: 'Villa Rosa' },
            { CiudadId: 9, NombreSector: 'Villa Francisca' },
            { CiudadId: 9, NombreSector: 'Ensanche Bermúdez' },
            { CiudadId: 9, NombreSector: 'Villa María' },
            { CiudadId: 9, NombreSector: 'Barrio Duarte' },
            { CiudadId: 9, NombreSector: 'Villa Padre las Casas' },
            { CiudadId: 9, NombreSector: 'Río Verde' },
            { CiudadId: 9, NombreSector: 'Pueblo Nuevo' },
            { CiudadId: 9, NombreSector: 'Villa Olga' },

            { CiudadId: 8, NombreSector: 'San Cristóbal Centro' },
            { CiudadId: 8, NombreSector: 'Cambita Garabitos' },
            { CiudadId: 8, NombreSector: 'Haina' },
            { CiudadId: 8, NombreSector: 'Najayo' },
            { CiudadId: 8, NombreSector: 'Bajos de Haina' },
            { CiudadId: 8, NombreSector: 'Villa Altagracia' },
            { CiudadId: 8, NombreSector: 'Palenque' },
            { CiudadId: 8, NombreSector: 'Sabana Grande de Palenque' },
            { CiudadId: 8, NombreSector: 'Yaguate' },
            { CiudadId: 8, NombreSector: 'Los Cacaos' },

            { CiudadId: 10, NombreSector: 'San Pedro de Macorís Centro' },
            { CiudadId: 10, NombreSector: 'Juan Dolio' },
            { CiudadId: 10, NombreSector: 'Guayacanes' },
            { CiudadId: 10, NombreSector: 'Consuelo' },
            { CiudadId: 10, NombreSector: 'Quisqueya' },
            { CiudadId: 10, NombreSector: 'Ramón Santana' },
            { CiudadId: 10, NombreSector: 'Los Llanos' },
            { CiudadId: 10, NombreSector: 'La Romana' },
            { CiudadId: 10, NombreSector: 'Villa Hermosa' },
            { CiudadId: 10, NombreSector: 'La Caleta' },

            { CiudadId: 11, NombreSector: 'Pueblo Nuevo' },
            { CiudadId: 11, NombreSector: 'La Javiela' },
            { CiudadId: 11, NombreSector: 'Vista del Valle' },
            { CiudadId: 11, NombreSector: 'La Altagracia' },
            { CiudadId: 11, NombreSector: 'Hermanas Mirabal' },
            { CiudadId: 11, NombreSector: 'San Martín' },
            { CiudadId: 11, NombreSector: 'Duarte' },
            { CiudadId: 11, NombreSector: 'La Ureña' },
            { CiudadId: 11, NombreSector: 'San Pedro' },
            { CiudadId: 11, NombreSector: 'Santa Ana' },

            { CiudadId: 12, NombreSector: 'Moca Centro' },
            { CiudadId: 12, NombreSector: 'Hermanas Mirabal' },
            { CiudadId: 12, NombreSector: 'Juan López Abajo' },
            { CiudadId: 12, NombreSector: 'Canca La Reyna' },
            { CiudadId: 12, NombreSector: 'José Contreras' },
            { CiudadId: 12, NombreSector: 'Espaillat' },
            { CiudadId: 12, NombreSector: 'La Vega' },
            { CiudadId: 12, NombreSector: 'Monte de la Jagua' },
            { CiudadId: 12, NombreSector: 'Villa Trina' },
            { CiudadId: 12, NombreSector: 'Higüerito' },

            { CiudadId: 13, NombreSector: 'Andrés' },
            { CiudadId: 13, NombreSector: 'La Caleta' },
            { CiudadId: 13, NombreSector: 'La Guáyiga' },
            { CiudadId: 13, NombreSector: 'Brisas del Mar' },
            { CiudadId: 13, NombreSector: 'Los Coquitos' },
            { CiudadId: 13, NombreSector: 'La Duarte' },
            { CiudadId: 13, NombreSector: 'La Caleta Beach' },
            { CiudadId: 13, NombreSector: 'La Caleta Marina' },
            { CiudadId: 13, NombreSector: 'San Rafael' },
            { CiudadId: 13, NombreSector: 'San Pedro' },

            { CiudadId: 14, NombreSector: 'Baní Centro' },
            { CiudadId: 14, NombreSector: 'Villa Majega' },
            { CiudadId: 14, NombreSector: 'Las Flores' },
            { CiudadId: 14, NombreSector: 'Villa Sombrero' },
            { CiudadId: 14, NombreSector: 'La Siembra' },
            { CiudadId: 14, NombreSector: 'Villa Fundación' },
            { CiudadId: 14, NombreSector: 'El Carretón' },
            { CiudadId: 14, NombreSector: 'Las Tablas' },
            { CiudadId: 14, NombreSector: 'Paya' },
            { CiudadId: 14, NombreSector: 'Villa Güera' },

            { CiudadId: 15, NombreSector: 'San Felipe de Puerto Plata' },
            { CiudadId: 15, NombreSector: 'Costámbar' },
            { CiudadId: 15, NombreSector: 'Playa Dorada' },
            { CiudadId: 15, NombreSector: 'Los Domínguez' },
            { CiudadId: 15, NombreSector: 'Long Beach' },
            { CiudadId: 15, NombreSector: 'Villa Isabela' },
            { CiudadId: 15, NombreSector: 'Luperón' },
            { CiudadId: 15, NombreSector: 'Maimón' },
            { CiudadId: 15, NombreSector: 'Sosúa' },
            { CiudadId: 15, NombreSector: 'Cabarete' },

            { CiudadId: 16, NombreSector: 'La Romana Centro' },
            { CiudadId: 16, NombreSector: 'Villa Hermosa' },
            { CiudadId: 16, NombreSector: 'Villa San Carlos' },
            { CiudadId: 16, NombreSector: 'La Caleta' },
            { CiudadId: 16, NombreSector: 'Cumayasa' },
            { CiudadId: 16, NombreSector: 'Bayahíbe' },
            { CiudadId: 16, NombreSector: 'Dominicus' },
            { CiudadId: 16, NombreSector: 'Villa Verde' },
            { CiudadId: 16, NombreSector: 'Guaymate' },
            { CiudadId: 16, NombreSector: 'El Caño' },

            { CiudadId: 17, NombreSector: 'Bajos de Haina Centro' },
            { CiudadId: 17, NombreSector: 'Cristo Rey' },
            { CiudadId: 17, NombreSector: 'La Barquita' },
            { CiudadId: 17, NombreSector: 'Los Solares' },
            { CiudadId: 17, NombreSector: 'Santa Rosa' },
            { CiudadId: 17, NombreSector: 'Los Mangos' },
            { CiudadId: 17, NombreSector: 'Los Barrancones' },
            { CiudadId: 17, NombreSector: 'Las Mercedes' },
            { CiudadId: 17, NombreSector: 'El Caliche' },
            { CiudadId: 17, NombreSector: 'Los Cocos' },

            { CiudadId: 18, NombreSector: 'Bonao Centro' },
            { CiudadId: 18, NombreSector: 'Ensanche Libertad' },
            { CiudadId: 18, NombreSector: 'Villa de Sonador' },
            { CiudadId: 18, NombreSector: 'La Altagracia' },
            { CiudadId: 18, NombreSector: 'Los Bajos de Haina' },
            { CiudadId: 18, NombreSector: 'Piedra Blanca' },
            { CiudadId: 18, NombreSector: 'El Cercado' },
            { CiudadId: 18, NombreSector: 'Jayaco' },
            { CiudadId: 18, NombreSector: 'Barrero' },
            { CiudadId: 18, NombreSector: 'La Salvia' },

            { CiudadId: 19, NombreSector: 'San Juan de la Maguana Centro' },
            { CiudadId: 19, NombreSector: 'Las Matas de Farfán' },
            { CiudadId: 19, NombreSector: 'El Cercado' },
            { CiudadId: 19, NombreSector: 'Hondo Valle' },
            { CiudadId: 19, NombreSector: 'Sabaneta' },
            { CiudadId: 19, NombreSector: 'El Rosario' },
            { CiudadId: 19, NombreSector: 'Pedro Corto' },
            { CiudadId: 19, NombreSector: 'Vallejuelo' },
            { CiudadId: 19, NombreSector: 'Juan de Herrera' },
            { CiudadId: 19, NombreSector: 'Las Charcas' },

            { CiudadId: 20, NombreSector: 'Villa Hermosa Centro' },
            { CiudadId: 20, NombreSector: 'La Altagracia' },
            { CiudadId: 20, NombreSector: 'El Libertador' },
            { CiudadId: 20, NombreSector: 'Los Cocos' },
            { CiudadId: 20, NombreSector: 'Los Maestros' },
            { CiudadId: 20, NombreSector: 'Villa Progreso' },
            { CiudadId: 20, NombreSector: 'La Fe' },
            { CiudadId: 20, NombreSector: 'La Unión' },
            { CiudadId: 20, NombreSector: 'Villa Cerro' },
            { CiudadId: 20, NombreSector: 'La Malena' },

            { CiudadId: 21, NombreSector: 'Villa Altagracia Centro' },
            { CiudadId: 21, NombreSector: 'Los Cocos' },
            { CiudadId: 21, NombreSector: 'El Libertador' },
            { CiudadId: 21, NombreSector: 'Villa Cerro' },
            { CiudadId: 21, NombreSector: 'La Fe' },
            { CiudadId: 21, NombreSector: 'Los Rosales' },
            { CiudadId: 21, NombreSector: 'Los Rieles' },
            { CiudadId: 21, NombreSector: 'El Cacique' },
            { CiudadId: 21, NombreSector: 'Los Tocones' },
            { CiudadId: 21, NombreSector: 'La Lomita' },

            { CiudadId: 22, NombreSector: 'Pedro Brand Centro' },
            { CiudadId: 22, NombreSector: 'La Cuaba' },
            { CiudadId: 22, NombreSector: 'La Guáyiga' },
            { CiudadId: 22, NombreSector: 'La Cuarenta' },
            { CiudadId: 22, NombreSector: 'Hacienda Estrella' },
            { CiudadId: 22, NombreSector: 'El Café' },
            { CiudadId: 22, NombreSector: 'Kilómetro 28' },
            { CiudadId: 22, NombreSector: 'Los Alcarrizos' },
            { CiudadId: 22, NombreSector: 'La Venta' },
            { CiudadId: 22, NombreSector: 'La Paz' },

            { CiudadId: 23, NombreSector: 'Barahona Centro' },
            { CiudadId: 23, NombreSector: 'Villa Central' },
            { CiudadId: 23, NombreSector: 'Santa Cruz de Barahona' },
            { CiudadId: 23, NombreSector: 'La Ciénaga' },
            { CiudadId: 23, NombreSector: 'El Peñón' },
            { CiudadId: 23, NombreSector: 'Palmar de Ocoa' },
            { CiudadId: 23, NombreSector: 'Paraíso' },
            { CiudadId: 23, NombreSector: 'Las Salinas' },
            { CiudadId: 23, NombreSector: 'El Cachón' },
            { CiudadId: 23, NombreSector: 'Canoa' },

            { CiudadId: 24, NombreSector: 'Mao Centro' },
            { CiudadId: 24, NombreSector: 'Esperanza' },
            { CiudadId: 24, NombreSector: 'Laguna Salada' },
            { CiudadId: 24, NombreSector: 'Jaibón' },
            { CiudadId: 24, NombreSector: 'Guatapanal' },
            { CiudadId: 24, NombreSector: 'Hatillo Palma' },
            { CiudadId: 24, NombreSector: 'El Higüerito' },
            { CiudadId: 24, NombreSector: 'Amina' },
            { CiudadId: 24, NombreSector: 'Boca de Mao' },
            { CiudadId: 24, NombreSector: 'Cruce de Esperanza' },

            { CiudadId: 25, NombreSector: 'Nagua Centro' },
            { CiudadId: 25, NombreSector: 'San José de Matanzas' },
            { CiudadId: 25, NombreSector: 'Cabrera' },
            { CiudadId: 25, NombreSector: 'El Factor' },
            { CiudadId: 25, NombreSector: 'Las Gordas' },
            { CiudadId: 25, NombreSector: 'Las Terrenas' },
            { CiudadId: 25, NombreSector: 'El Juncalito' },
            { CiudadId: 25, NombreSector: 'El Factor' },
            { CiudadId: 25, NombreSector: 'Los Robalos' },
            { CiudadId: 25, NombreSector: 'Matancitas' },

            { CiudadId: 26, NombreSector: 'Cotuí Centro' },
            { CiudadId: 26, NombreSector: 'Pueblo Viejo' },
            { CiudadId: 26, NombreSector: 'Cevicos' },
            { CiudadId: 26, NombreSector: 'La Mata' },
            { CiudadId: 26, NombreSector: 'Los Almendros' },
            { CiudadId: 26, NombreSector: 'Caballero' },
            { CiudadId: 26, NombreSector: 'Villa La Mata' },
            { CiudadId: 26, NombreSector: 'Quita Sueño' },
            { CiudadId: 26, NombreSector: 'La Granja' },
            { CiudadId: 26, NombreSector: 'Los Toros' },

            { CiudadId: 27, NombreSector: 'El Seibo Centro' },
            { CiudadId: 27, NombreSector: 'Miches' },
            { CiudadId: 27, NombreSector: 'Santa Cruz de El Seibo' },
            { CiudadId: 27, NombreSector: 'Higüeyito' },
            { CiudadId: 27, NombreSector: 'Pedro Sánchez' },
            { CiudadId: 27, NombreSector: 'Vicentillo' },
            { CiudadId: 27, NombreSector: 'Mocha' },
            { CiudadId: 27, NombreSector: 'La Higuera' },
            { CiudadId: 27, NombreSector: 'Santa Lucía' },
            { CiudadId: 27, NombreSector: 'Guaymate' },

            { CiudadId: 28, NombreSector: 'Esperanza Centro' },
            { CiudadId: 28, NombreSector: 'Maizal' },
            { CiudadId: 28, NombreSector: 'Boca de Mao' },
            { CiudadId: 28, NombreSector: 'Jicomé' },
            { CiudadId: 28, NombreSector: 'Tenares' },
            { CiudadId: 28, NombreSector: 'Blanco Arriba' },
            { CiudadId: 28, NombreSector: 'Tireo' },
            { CiudadId: 28, NombreSector: 'Cruce de Esperanza' },
            { CiudadId: 28, NombreSector: 'Laguna Salada' },
            { CiudadId: 28, NombreSector: 'Jaibón' },

            { CiudadId: 29, NombreSector: 'Samaná Centro' },
            { CiudadId: 29, NombreSector: 'Las Terrenas' },
            { CiudadId: 29, NombreSector: 'Santa Bárbara de Samaná' },
            { CiudadId: 29, NombreSector: 'Las Galeras' },
            { CiudadId: 29, NombreSector: 'El Limón' },
            { CiudadId: 29, NombreSector: 'El Cedro' },
            { CiudadId: 29, NombreSector: 'El Valle' },
            { CiudadId: 29, NombreSector: 'Arroyo Barril' },
            { CiudadId: 29, NombreSector: 'Las Galeras' },
            { CiudadId: 29, NombreSector: 'El Rincón' },

            { CiudadId: 30, NombreSector: 'Hato Mayor del Rey' },
            { CiudadId: 30, NombreSector: 'Sabana de la Mar' },
            { CiudadId: 30, NombreSector: 'El Valle' },
            { CiudadId: 30, NombreSector: 'Yerba Buena' },
            { CiudadId: 30, NombreSector: 'Majagual' },
            { CiudadId: 30, NombreSector: 'Guayabo Dulce' },
            { CiudadId: 30, NombreSector: 'Mata Palacio' },
            { CiudadId: 30, NombreSector: 'Los Hatillos' },
            { CiudadId: 30, NombreSector: 'Elupina Cordero de Las Cañitas' },
            { CiudadId: 30, NombreSector: 'Mata de Palma' },

            { CiudadId: 31, NombreSector: 'Constanza Centro' },
            { CiudadId: 31, NombreSector: 'La Ciénaga' },
            { CiudadId: 31, NombreSector: 'Tireo' },
            { CiudadId: 31, NombreSector: 'Sabaneta de Constanza' },
            { CiudadId: 31, NombreSector: 'El Valle' },
            { CiudadId: 31, NombreSector: 'La Florida' },
            { CiudadId: 31, NombreSector: 'La Culata' },
            { CiudadId: 31, NombreSector: 'Los Cacaos' },
            { CiudadId: 31, NombreSector: 'El Uvero' },
            { CiudadId: 31, NombreSector: 'La Altagracia' },

            { CiudadId: 32, NombreSector: 'Jarabacoa Centro' },
            { CiudadId: 32, NombreSector: 'Manabao' },
            { CiudadId: 32, NombreSector: 'Buena Vista' },
            { CiudadId: 32, NombreSector: 'La Joya' },
            { CiudadId: 32, NombreSector: 'El Salto' },
            { CiudadId: 32, NombreSector: 'Jamao' },
            { CiudadId: 32, NombreSector: 'Jácquez Abajo' },
            { CiudadId: 32, NombreSector: 'El Café' },
            { CiudadId: 32, NombreSector: 'Rincón' },
            { CiudadId: 32, NombreSector: 'El Bronce' },

            { CiudadId: 33, NombreSector: 'Yamasá Centro' },
            { CiudadId: 33, NombreSector: 'Los Fríos' },
            { CiudadId: 33, NombreSector: 'Don Gregorio' },
            { CiudadId: 33, NombreSector: 'Los Robles' },
            { CiudadId: 33, NombreSector: 'Los Barrancos' },
            { CiudadId: 33, NombreSector: 'Las Auyamas' },
            { CiudadId: 33, NombreSector: 'El Rosario' },
            { CiudadId: 33, NombreSector: 'Los López' },
            { CiudadId: 33, NombreSector: 'Higüerito' },
            { CiudadId: 33, NombreSector: 'La Atravesada' },

            { CiudadId: 34, NombreSector: 'Tamboril Centro' },
            { CiudadId: 34, NombreSector: 'La Sección' },
            { CiudadId: 34, NombreSector: 'El Licey' },
            { CiudadId: 34, NombreSector: 'Palo Amarillo' },
            { CiudadId: 34, NombreSector: 'Canca de Yaque' },
            { CiudadId: 34, NombreSector: 'El Mamey' },
            { CiudadId: 34, NombreSector: 'El Aguacate' },
            { CiudadId: 34, NombreSector: 'La Joya' },
            { CiudadId: 34, NombreSector: 'Gurabo Abajo' },
            { CiudadId: 34, NombreSector: 'La Zurza' },

            { CiudadId: 35, NombreSector: 'San Antonio de Guerra Centro' },
            { CiudadId: 35, NombreSector: 'Quita Sueño' },
            { CiudadId: 35, NombreSector: 'Boca Chica' },
            { CiudadId: 35, NombreSector: 'Los Cocos' },
            { CiudadId: 35, NombreSector: 'La Ciénaga' },
            { CiudadId: 35, NombreSector: 'La Cuaba' },
            { CiudadId: 35, NombreSector: 'El Café' },
            { CiudadId: 35, NombreSector: 'Villa Liberación' },
            { CiudadId: 35, NombreSector: 'Mata de Palma' },
            { CiudadId: 35, NombreSector: 'Los Fríos' },

            { CiudadId: 36, NombreSector: 'Sosúa Centro' },
            { CiudadId: 36, NombreSector: 'El Batey' },
            { CiudadId: 36, NombreSector: 'La Unión' },
            { CiudadId: 36, NombreSector: 'Los Charamicos' },
            { CiudadId: 36, NombreSector: 'La Mulata' },
            { CiudadId: 36, NombreSector: 'Los Cerros' },
            { CiudadId: 36, NombreSector: 'Monte Chiquito' },
            { CiudadId: 36, NombreSector: 'Abreu' },
            { CiudadId: 36, NombreSector: 'Los Castillos' },
            { CiudadId: 36, NombreSector: 'Maimón' },

            { CiudadId: 37, NombreSector: 'Puñal Centro' },
            { CiudadId: 37, NombreSector: 'La Herradura' },
            { CiudadId: 37, NombreSector: 'El Tablón' },
            { CiudadId: 37, NombreSector: 'Sabaneta de Cangrejos' },
            { CiudadId: 37, NombreSector: 'El Limón' },
            { CiudadId: 37, NombreSector: 'La Canela' },
            { CiudadId: 37, NombreSector: 'Monte Adentro' },
            { CiudadId: 37, NombreSector: 'La Rancheta' },
            { CiudadId: 37, NombreSector: 'Palo Amarillo' },
            { CiudadId: 37, NombreSector: 'Hacienda Estrella' },

            { CiudadId: 38, NombreSector: 'Monte Plata Centro' },
            { CiudadId: 38, NombreSector: 'Bayaguana' },
            { CiudadId: 38, NombreSector: 'Yamasá' },
            { CiudadId: 38, NombreSector: 'Saban Grande de Boyá' },
            { CiudadId: 38, NombreSector: 'Chirino' },
            { CiudadId: 38, NombreSector: 'Peralvillo' },
            { CiudadId: 38, NombreSector: 'Gonzalo' },
            { CiudadId: 38, NombreSector: 'Don Juan' },
            { CiudadId: 38, NombreSector: 'Majagual' },
            { CiudadId: 38, NombreSector: 'La Gina' },

            { CiudadId: 39, NombreSector: 'Villa Bisonó Centro' },
            { CiudadId: 39, NombreSector: 'La Otra Banda' },
            { CiudadId: 39, NombreSector: 'El Ingenio' },
            { CiudadId: 39, NombreSector: 'La Hondonada' },
            { CiudadId: 39, NombreSector: 'La Ceja' },
            { CiudadId: 39, NombreSector: 'Higüero' },
            { CiudadId: 39, NombreSector: 'Las Palomas' },
            { CiudadId: 39, NombreSector: 'Guaraguao' },
            { CiudadId: 39, NombreSector: 'Gurabo' },
            { CiudadId: 39, NombreSector: 'Pontón' },

            { CiudadId: 40, NombreSector: 'Las Matas de Farfán Centro' },
            { CiudadId: 40, NombreSector: 'Cabeza de Toro' },
            { CiudadId: 40, NombreSector: 'Juan de Herrera' },
            { CiudadId: 40, NombreSector: 'El Cercado' },
            { CiudadId: 40, NombreSector: 'El Peñón' },
            { CiudadId: 40, NombreSector: 'Guayabal' },
            { CiudadId: 40, NombreSector: 'Los Montones' },
            { CiudadId: 40, NombreSector: 'El Limonal' },
            { CiudadId: 40, NombreSector: 'La Guázuma' },
            { CiudadId: 40, NombreSector: 'El Palmar' },

            { CiudadId: 41, NombreSector: 'San José de las Matas Centro' },
            { CiudadId: 41, NombreSector: 'El Rubio' },
            { CiudadId: 41, NombreSector: 'Las Placetas' },
            { CiudadId: 41, NombreSector: 'El Cercado' },
            { CiudadId: 41, NombreSector: 'El Higo' },
            { CiudadId: 41, NombreSector: 'La Ciénaga' },
            { CiudadId: 41, NombreSector: 'Los Jovillos' },
            { CiudadId: 41, NombreSector: 'La Culata' },
            { CiudadId: 41, NombreSector: 'La Siberia' },
            { CiudadId: 41, NombreSector: 'La Piña' },
            { CiudadId: 42, NombreSector: 'Salcedo Centro' },
            { CiudadId: 42, NombreSector: 'Tenares' },
            { CiudadId: 42, NombreSector: 'Villa Tapia' },
            { CiudadId: 42, NombreSector: 'La Canela' },
            { CiudadId: 42, NombreSector: 'El Puerto' },
            { CiudadId: 42, NombreSector: 'Agua Santa del Yuna' },
            { CiudadId: 42, NombreSector: 'La Jagua' },
            { CiudadId: 42, NombreSector: 'Los Rieles' },
            { CiudadId: 42, NombreSector: 'Arenoso' },
            { CiudadId: 42, NombreSector: 'Castillo' },

            { CiudadId: 43, NombreSector: 'La Mata Centro' },
            { CiudadId: 43, NombreSector: 'Jumunucú' },
            { CiudadId: 43, NombreSector: 'La Gina' },
            { CiudadId: 43, NombreSector: 'Sabana Grande' },
            { CiudadId: 43, NombreSector: 'El Cerro' },
            { CiudadId: 43, NombreSector: 'Los Montones' },
            { CiudadId: 43, NombreSector: 'La Guama' },
            { CiudadId: 43, NombreSector: 'Las Lagunas' },
            { CiudadId: 43, NombreSector: 'El Jovito' },
            { CiudadId: 43, NombreSector: 'La Compuerta' },

            { CiudadId: 44, NombreSector: 'Gaspar Hernández Centro' },
            { CiudadId: 44, NombreSector: 'Cabarete' },
            { CiudadId: 44, NombreSector: 'Rincón' },
            { CiudadId: 44, NombreSector: 'La Ciénaga' },
            { CiudadId: 44, NombreSector: 'Magante' },
            { CiudadId: 44, NombreSector: 'Veragua' },
            { CiudadId: 44, NombreSector: 'Abreu' },
            { CiudadId: 44, NombreSector: 'La Granja' },
            { CiudadId: 44, NombreSector: 'La Tuna' },
            { CiudadId: 44, NombreSector: 'Veragua' },

            { CiudadId: 45, NombreSector: 'Guayubín Centro' },
            { CiudadId: 45, NombreSector: 'La Caya' },
            { CiudadId: 45, NombreSector: 'Las Cañitas' },
            { CiudadId: 45, NombreSector: 'Los Higos' },
            { CiudadId: 45, NombreSector: 'Hondo Valle' },
            { CiudadId: 45, NombreSector: 'Palo Blanco' },
            { CiudadId: 45, NombreSector: 'Juan Gómez' },
            { CiudadId: 45, NombreSector: 'Hacienda Estrella' },
            { CiudadId: 45, NombreSector: 'La Peña' },
            { CiudadId: 45, NombreSector: 'Higüerito' },

            { CiudadId: 46, NombreSector: 'Neiba Centro' },
            { CiudadId: 46, NombreSector: 'Galván' },
            { CiudadId: 46, NombreSector: 'Tamayo' },
            { CiudadId: 46, NombreSector: 'El Palmar' },
            { CiudadId: 46, NombreSector: 'Juancho' },
            { CiudadId: 46, NombreSector: 'Los Robles' },
            { CiudadId: 46, NombreSector: 'Uvilla' },
            { CiudadId: 46, NombreSector: 'Postrer Río' },
            { CiudadId: 46, NombreSector: 'Las Clavellinas' },
            { CiudadId: 46, NombreSector: 'Sabana Larga' },

            { CiudadId: 47, NombreSector: 'San José de Ocoa Centro' },
            { CiudadId: 47, NombreSector: 'Rancho Arriba' },
            { CiudadId: 47, NombreSector: 'El Pinar' },
            { CiudadId: 47, NombreSector: 'Nizao-Las Auyamas' },
            { CiudadId: 47, NombreSector: 'La Ciénaga' },
            { CiudadId: 47, NombreSector: 'El Naranjal' },
            { CiudadId: 47, NombreSector: 'El Cercado' },
            { CiudadId: 47, NombreSector: 'El Mogote' },
            { CiudadId: 47, NombreSector: 'El Pinar' },
            { CiudadId: 47, NombreSector: 'Rancho Arriba' },

            { CiudadId: 48, NombreSector: 'Villa Riva Centro' },
            { CiudadId: 48, NombreSector: 'Pimentel' },
            { CiudadId: 48, NombreSector: 'Matanzas' },
            { CiudadId: 48, NombreSector: 'La Bija' },
            { CiudadId: 48, NombreSector: 'El Toro' },
            { CiudadId: 48, NombreSector: 'Las Auyamas' },
            { CiudadId: 48, NombreSector: 'Sabana Cruz' },
            { CiudadId: 48, NombreSector: 'Sabana Grande' },
            { CiudadId: 48, NombreSector: 'El Cercado' },
            { CiudadId: 48, NombreSector: 'La Zanja' },

            { CiudadId: 49, NombreSector: 'San Ignacio de Sabaneta Centro' },
            { CiudadId: 49, NombreSector: 'La Descubierta' },
            { CiudadId: 49, NombreSector: 'Los Arroyos' },
            { CiudadId: 49, NombreSector: 'Villa Los Almácigos' },
            { CiudadId: 49, NombreSector: 'Dajabón' },
            { CiudadId: 49, NombreSector: 'Loma de Cabrera' },
            { CiudadId: 49, NombreSector: 'Santiago de la Cruz' },
            { CiudadId: 49, NombreSector: 'La Loma' },
            { CiudadId: 49, NombreSector: 'Hondo Valle' },
            { CiudadId: 49, NombreSector: 'La Ceiba' },

            { CiudadId: 50, NombreSector: 'Bayaguana Centro' },
            { CiudadId: 50, NombreSector: 'Monte Plata' },
            { CiudadId: 50, NombreSector: 'Gonzalo' },
            { CiudadId: 50, NombreSector: 'El Jobo' },
            { CiudadId: 50, NombreSector: 'El Naranjo' },
            { CiudadId: 50, NombreSector: 'Los Mangos' },
            { CiudadId: 50, NombreSector: 'Los Botados' },
            { CiudadId: 50, NombreSector: 'La Rueda' },
            { CiudadId: 50, NombreSector: 'Los Mameyes' },
            { CiudadId: 50, NombreSector: 'Los Cajuiles' },

            { CiudadId: 51, NombreSector: 'Dajabón Centro' },
            { CiudadId: 51, NombreSector: 'Loma de Cabrera' },
            { CiudadId: 51, NombreSector: 'Partido' },
            { CiudadId: 51, NombreSector: 'Cañongo' },
            { CiudadId: 51, NombreSector: 'El Pino' },
            { CiudadId: 51, NombreSector: 'Restauración' },
            { CiudadId: 51, NombreSector: 'Amina' },
            { CiudadId: 51, NombreSector: 'La Bomba' },
            { CiudadId: 51, NombreSector: 'El Cercado' },
            { CiudadId: 51, NombreSector: 'Sabanalarga' },

            { CiudadId: 52, NombreSector: 'Tenares Centro' },
            { CiudadId: 52, NombreSector: 'La Peña' },
            { CiudadId: 52, NombreSector: 'Castillo' },
            { CiudadId: 52, NombreSector: 'Juncalito' },
            { CiudadId: 52, NombreSector: 'La Bija' },
            { CiudadId: 52, NombreSector: 'La Jagua' },
            { CiudadId: 52, NombreSector: 'Villa Tapia' },
            { CiudadId: 52, NombreSector: 'El Capá' },
            { CiudadId: 52, NombreSector: 'El Piñal' },
            { CiudadId: 52, NombreSector: 'La Culata' },

            { CiudadId: 53, NombreSector: 'Villa González Centro' },
            { CiudadId: 53, NombreSector: 'La Canela' },
            { CiudadId: 53, NombreSector: 'Punaló' },
            { CiudadId: 53, NombreSector: 'Navarrete' },
            { CiudadId: 53, NombreSector: 'Licey al Medio' },
            { CiudadId: 53, NombreSector: 'Santiago Oeste' },
            { CiudadId: 53, NombreSector: 'Santiago Rodríguez' },
            { CiudadId: 53, NombreSector: 'Canca la Piedra' },
            { CiudadId: 53, NombreSector: 'Los Ciruelitos' },
            { CiudadId: 53, NombreSector: 'San Francisco' },

            { CiudadId: 54, NombreSector: 'Monte Cristi Centro' },
            { CiudadId: 54, NombreSector: 'Pepillo Salcedo' },
            { CiudadId: 54, NombreSector: 'Castañuelas' },
            { CiudadId: 54, NombreSector: 'Guayubín' },
            { CiudadId: 54, NombreSector: 'Palo Verde' },
            { CiudadId: 54, NombreSector: 'Villa Elisa' },
            { CiudadId: 54, NombreSector: 'Higüerito' },
            { CiudadId: 54, NombreSector: 'Juan Gómez' },
            { CiudadId: 54, NombreSector: 'Las Matas de Santa Cruz' },
            { CiudadId: 54, NombreSector: 'La Cañita' },

            { CiudadId: 18, NombreSector: 'Los Cacaitos' },
            { CiudadId: 18, NombreSector: 'El Tamarindo' },
            { CiudadId: 18, NombreSector: 'Ensanche Duarte' },
            { CiudadId: 18, NombreSector: 'Las Delicias' },

            { CiudadId: 58, NombreSector: 'Los Cajuiles' },
            { CiudadId: 58, NombreSector: 'Los Guayuyos' },
            { CiudadId: 58, NombreSector: 'El Hatillo' },
            { CiudadId: 58, NombreSector: 'Villa Progreso' },

            { CiudadId: 59, NombreSector: 'La Gina' },
            { CiudadId: 59, NombreSector: 'Los Pomos' },
            { CiudadId: 59, NombreSector: 'El Higüero' },
            { CiudadId: 59, NombreSector: 'Monte Adentro' },

            { CiudadId: 60, NombreSector: 'Sabana del Medio' },
            { CiudadId: 60, NombreSector: 'Las Cañitas' },
            { CiudadId: 60, NombreSector: 'El Fundo' },
            { CiudadId: 60, NombreSector: 'La Culata' },

            { CiudadId: 55, NombreSector: 'Los Pinos' },
            { CiudadId: 55, NombreSector: 'La Bombita' },
            { CiudadId: 55, NombreSector: 'Los Coquitos' },
            { CiudadId: 55, NombreSector: 'Barrio Duarte' },

            { CiudadId: 55, NombreSector: 'La Cuarenta' },
            { CiudadId: 55, NombreSector: 'Los Almendros' },
            { CiudadId: 55, NombreSector: 'Barrio San Juan' },
            { CiudadId: 55, NombreSector: 'Los Mangos' },

            { CiudadId: 56, NombreSector: 'Villa Tapia' },
            { CiudadId: 56, NombreSector: 'El Guanábano' },
            { CiudadId: 56, NombreSector: 'La Lometa' },
            { CiudadId: 56, NombreSector: 'Villa de la Mina' },

            { CiudadId: 57, NombreSector: 'La Gallera' },
            { CiudadId: 57, NombreSector: 'Los Pomos' },
            { CiudadId: 57, NombreSector: 'El Higüero' },
            { CiudadId: 57, NombreSector: 'Los Manguitos' },

            { CiudadId: 61, NombreSector: 'Barrio La Cañada' },
            { CiudadId: 61, NombreSector: 'Barrio Norte' },
            { CiudadId: 61, NombreSector: 'Villa Estela' },
            { CiudadId: 61, NombreSector: 'Barrio La Altagracia' },

            { CiudadId: 62, NombreSector: 'Barrio El Centro' },
            { CiudadId: 62, NombreSector: 'Los Tramos' },
            { CiudadId: 62, NombreSector: 'El Mamón' },
            { CiudadId: 62, NombreSector: 'La Guama' },

            { CiudadId: 63, NombreSector: 'Barrio Nuevo' },
            { CiudadId: 63, NombreSector: 'La Ceiba' },
            { CiudadId: 63, NombreSector: 'El Cajuilito' },
            { CiudadId: 63, NombreSector: 'La Ciénaga' },

            { CiudadId: 64, NombreSector: 'El Pinar' },
            { CiudadId: 64, NombreSector: 'Villa Isabela' },
            { CiudadId: 64, NombreSector: 'El Higüero' },
            { CiudadId: 64, NombreSector: 'Barrio Sur' },

            { CiudadId: 65, NombreSector: 'Barrio La Playa' },
            { CiudadId: 65, NombreSector: 'Villa Central' },
            { CiudadId: 65, NombreSector: 'Barrio Norte' },
            { CiudadId: 65, NombreSector: 'Barrio El Sol' },

            { CiudadId: 66, NombreSector: 'Los Arroyos' },
            { CiudadId: 66, NombreSector: 'El Limón' },
            { CiudadId: 66, NombreSector: 'El Cajuil' },
            { CiudadId: 66, NombreSector: 'Villa Jeremías' },

            { CiudadId: 67, NombreSector: 'La Ciénaga' },
            { CiudadId: 67, NombreSector: 'El Naranjo' },
            { CiudadId: 67, NombreSector: 'Villa Nueva' },
            { CiudadId: 67, NombreSector: 'Barrio Juancho' }

        ];

        await Sector.bulkCreate(sectorsData, { transaction: t });


        await Frequency.bulkCreate([
            { FrequencyId: 1, Name: 'Weekly', Fnumber: 7 },
            { FrequencyId: 2, Name: 'Bi-Weekly', Fnumber: 14 },
            { FrequencyId: 3, Name: 'Monthly', Fnumber: 30 },
            { FrequencyId: 4, Name: 'Quarterly', Fnumber: 90 },
            { FrequencyId: 5, Name: 'Semi-Annually', Fnumber: 180 },
            { FrequencyId: 6, Name: 'Annually', Fnumber: 365 },
        ], { transaction: t });

        await LoanState.bulkCreate([
            { Name: 'Pending' },
            { Name: 'Paid' },
            { Name: 'Late' },
            { Name: 'Partial' },
            { Name: 'Under Review' },
            { Name: 'Approved' },
            { Name: 'Rejected' },
            { Name: 'Cancelled' },
            { Name: 'In Progress' },
            { Name: 'Closed' },
            { Name: 'Refunded' },
            { Name: 'Defaulted' },
        ], { transaction: t });
        // Si llegamos aquí, la transacción se completa con éxito
        await t.commit();
        return res.status(200).json({
            ok: true,
            msg: 'Inserciones exitosas en todas las tablas'
        });
    } catch (error) {
        // Si hay algún error, deshacemos la transacción
        await t.rollback();
        return res.status(500).json({ ok: false, msg: 'Error al realizar las inserciones:' + error.message });
    }
};

export const Information = async (req, res) => {
    try {
        const data = {
            userTypes: await UserType.findAll(),
            paises: await Pais.findAll(),
            maRegions: await MARegion.findAll(),
            miRegions: await MIRegion.findAll(),
            provincias: await Provincia.findAll(),
            ciudades: await Ciudad.findAll(),
            Sectores: await Sector.findAll(),
            frequencies: await Frequency.findAll(),
            loanStates: await LoanState.findAll()
        };

        res.json({ok:true, data});
    } catch (error) {
        console.error('Error al obtener la información:', error);
        res.status(500).json({ error: 'Error interno del servidor' });
    }
};