version: '3.4'

services:
  loanpg:
    image: postgres:14
    env_file: ./.env
    container_name: loanpg
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
    - ./postgres:/data/loanpg    

  loanapi:
    depends_on:
      - loanpg
    links:
      - loanpg
    build: 
      context: .
      dockerfile: Dockerfile
    image: loanapi-docker
    container_name: loanapi
    restart: always
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:$POSTGRES_PORT/$POSTGRES_DATABASE
    
   
